### ISSUE TITLE
federate should find default configuration and logger in target/conf

### ISSUE THREAD

**Issue by MartyBurns** [SimIntToolkit/cpswt-core#63]
Currently, if no environmental variable is set or command line parameter provided, no config file is found even though the code generator places a default configuration file in the conf directory. Same for the log4j2.xml file.

I think we should extend FederateConfigParser.parseCommandLine()  to default to that file if no command line or environmental parameter is provided.

I believe right now it gives up.

**Comment by hnine999** [comment]
Obsolete, as code-generate has been completely rewritten.
