### ISSUE TITLE
Check if handle of inherited property in derived HLA class is same/different from handle of same property in base HLA class

### ISSUE THREAD

**Issue by tpr1** [SimIntToolkit/cpswt-core#80]
A derived interaction/object class uses a different handle for parameters/attributes inherited from a parent class. So if InteractionA defines parameter 1, and InteractionB inherits parameter 1 from InteractionA, the parameter InteractionA.1 will have a different handle than InteractionB.1

The current code, both static and WebGME generated, does not handle this difference in the method setParameterAux / setAttributeAux. The implementation of both methods should be extended to check for all possible parameter handles - even those inherited from parent classes - before handing the call over to the super class implementation.

**Comment by hnine999** [comment]
As the Java-code generator has been completely rewritten, this issue is obsolete.
